name: CI/CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout V2
        uses: actions/checkout@v2
      - name: Setup Node V2
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Clean Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build Scripts
        run: npm run build
      - name: Unit Test
        run: npm run test
      - name: Build Demo
        run: npm run demo
      - name: Integration tests
        run: npm run e2e:ci
      - name: Release
        if: ${{ !env.ACT }}
        run: npx semantic-release --branches master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
