name: CI
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Clean Install
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Build Distribution
        run: npm run build
      - name: Build Demo
        run: npm run demo
      - name: Unit Test
        run: npm run test -- --coverage
      - name: Integration Test
        run: npm run e2e:ci
      - name: Release
        if: github.ref == 'refs/heads/master'
        run: npx semantic-release@19.0.5 --branches master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
