name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install node dependancies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Typescript build
      run: npm run ts
    - name: Unit test
      run: npm run test
    - name: Integration test
      run: npm run e2e:ci
    - name: Semantic release
      run: npx semantic-release --branches master
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}