name: CI/CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout v2
        uses: actions/checkout@v2
      - name: setup node v2
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: clean install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: build app
        run: npm run build
      - name: unit test
        run: npm run test
      - name: end to end tests
        run: npm run e2e:ci
      - name: semantic release
        if: ${{ !env.ACT }}
        run: npx semantic-release --branches master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
